[package]
name = "pb-atomic-linked-list"
version = "0.1.6"
edition = "2021"
description = "An atomic insert-only linked list"
license-file = "LICENSE.txt"
categories = ["memory-management"]
homepage = "https://github.com/gpabois/rs-pb-atomic-linked-list"

[dependencies]
